baseURL = "https://sandeep-mars.github.io/my-portfolio-new/"
languageCode = "en-us"
title = "Sandeep Mars | Data Engineer"
theme = "terminal"

[params]
  themeColor = "blue"
  contentTypeName = "projects"
  showLogo = true
  showMenu = true

[languages.en]
  title = "Sandeep Mars"
  subtitle = "Data Engineer | Politecnico di Milano Alum"
