baseURL = "https://sandeep-mars.github.io/my-portfolio-new/"
languageCode = "en-us"
title = "Sandeep Mars | Data Engineer"
theme = "terminal"

[params]
  # Theme color options: blue, orange, red, green, pink
  themeColor = "blue"
  contentTypeName = "projects"
  showLastUpdated = true
  showReadingTime = false
  showLogo = true
  showMenu = true

[languages]
  [languages.en]
    title = "Sandeep Mars"
    subtitle = "Data Engineer | Infrastructure & Real-Time Streaming"
    keywords = ["Data Engineer", "Terraform", "PySpark", "Azure"]
    copyright = "Â© 2026 Sandeep Mars"

    [languages.en.params.logo]
      logoText = "Sandeep@Mars: ~$"
      logoHomeLink = "/"

    [[languages.en.menu.main]]
      name = "Projects"
      url = "/projects"
